print('My name is Alex Li.')
print('I was born in November')
print('My favorite food is tacos')
print('My favorite music is pop')
print('My astrological sign is scorpio')
print('My name is Geoff Pottow')
print('I was born in July')
